language: rust

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        -rust: nightly

before_install:
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
    - sudo apt-get update -qq
    - sudo apt-get install -qq libsdl2-dev
