// Copyright 2016 Peter Beard
// Distributed under the GNU GPL v3. For full terms, see the LICENSE file.
//
// Opcodes and function for mapping bytes to opcodes

#[derive(Eq, PartialEq, Debug, Clone, Copy)]
pub enum Opcode {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    KIL,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TYA,
    TSX,
    TXA,
    TXS,
    // undocumented instructions
    SLO,
    RLA,
    SRE,
    RRA,
    SAX,
    LAX,
    DCP,
    ISC,
    ANC,
    ALR,
    ARR,
    XAA,
    AXS,
    AHX,
    SHY,
    SHX,
    TAS,
    LAS,
}

impl Opcode {
    pub fn from_u8(code: u8) -> Opcode {
        use self::Opcode::*;
        match code {
            0x00 => BRK,
            0x01 => ORA,
            0x02 => KIL,
            0x03 => SLO,
            0x04 => NOP,
            0x05 => ORA,
            0x06 => ASL,
            0x07 => SLO,
            0x08 => PHP,
            0x09 => ORA,
            0x0a => ASL,
            0x0b => ANC,
            0x0c => NOP,
            0x0d => ORA,
            0x0e => ASL,
            0x0f => SLO,

            0x10 => BPL,
            0x11 => ORA,
            0x12 => KIL,
            0x13 => SLO,
            0x14 => NOP,
            0x15 => ORA,
            0x16 => ASL,
            0x17 => SLO,
            0x18 => CLC,
            0x19 => ORA,
            0x1a => NOP,
            0x1b => SLO,
            0x1c => NOP,
            0x1d => ORA,
            0x1e => ASL,
            0x1f => SLO,

            0x20 => JSR,
            0x21 => AND,
            0x22 => KIL,
            0x23 => RLA,
            0x24 => BIT,
            0x25 => AND,
            0x26 => ROL,
            0x27 => RLA,
            0x28 => PLP,
            0x29 => AND,
            0x2a => ROL,
            0x2b => AND,
            0x2c => BIT,
            0x2d => AND,
            0x2e => ROL,
            0x2f => RLA,

            0x30 => BMI,
            0x31 => AND,
            0x32 => KIL,
            0x33 => RLA,
            0x34 => NOP,
            0x35 => AND,
            0x36 => ROL,
            0x37 => RLA,
            0x38 => SEC,
            0x39 => AND,
            0x3a => NOP,
            0x3b => RLA,
            0x3c => NOP,
            0x3d => AND,
            0x3e => ROL,
            0x3f => RLA,

            0x40 => RTI,
            0x41 => EOR,
            0x42 => KIL,
            0x43 => SRE,
            0x44 => NOP,
            0x45 => EOR,
            0x46 => LSR,
            0x47 => SRE,
            0x48 => PHA,
            0x49 => EOR,
            0x4a => LSR,
            0x4b => ALR,
            0x4c => JMP,
            0x4d => EOR,
            0x4e => LSR,
            0x4f => SRE,

            0x50 => BVC,
            0x51 => EOR,
            0x52 => KIL,
            0x53 => SRE,
            0x54 => NOP,
            0x55 => EOR,
            0x56 => LSR,
            0x57 => SRE,
            0x58 => CLI,
            0x59 => EOR,
            0x5a => NOP,
            0x5b => SRE,
            0x5c => NOP,
            0x5d => EOR,
            0x5e => LSR,
            0x5f => SRE,

            0x60 => RTS,
            0x61 => ADC,
            0x62 => KIL,
            0x63 => RRA,
            0x64 => NOP,
            0x65 => ADC,
            0x66 => ROR,
            0x67 => RRA,
            0x68 => PLA,
            0x69 => ADC,
            0x6a => ROR,
            0x6b => ARR,
            0x6c => JMP,
            0x6d => ADC,
            0x6e => ROR,
            0x6f => RRA,

            0x70 => BVS,
            0x71 => ADC,
            0x72 => KIL,
            0x73 => RRA,
            0x74 => NOP,
            0x75 => ADC,
            0x76 => ROR,
            0x77 => RRA,
            0x78 => SEI,
            0x79 => ADC,
            0x7a => NOP,
            0x7b => RRA,
            0x7c => NOP,
            0x7d => ADC,
            0x7e => ROR,
            0x7f => RRA,

            0x80 => NOP,
            0x81 => STA,
            0x82 => NOP,
            0x83 => SAX,
            0x84 => STY,
            0x85 => STA,
            0x86 => STX,
            0x87 => SAX,
            0x88 => DEY,
            0x89 => NOP,
            0x8a => TXA,
            0x8b => XAA,
            0x8c => STY,
            0x8d => STA,
            0x8e => STX,
            0x8f => SAX,

            0x90 => BCC,
            0x91 => STA,
            0x92 => KIL,
            0x93 => AHX,
            0x94 => STY,
            0x95 => STA,
            0x96 => STX,
            0x97 => SAX,
            0x98 => TYA,
            0x99 => STA,
            0x9a => TXS,
            0x9b => TAS,
            0x9c => SHY,
            0x9d => STA,
            0x9e => SHX,
            0x9f => AHX,

            0xa0 => LDY,
            0xa1 => LDA,
            0xa2 => LDX,
            0xa3 => LAX,
            0xa4 => LDY,
            0xa5 => LDA,
            0xa6 => LDX,
            0xa7 => LAX,
            0xa8 => TAY,
            0xa9 => LDA,
            0xaa => TAX,
            0xab => LAX,
            0xac => LDY,
            0xad => LDA,
            0xae => LDX,
            0xaf => LAX,

            0xb0 => BCS,
            0xb1 => LDA,
            0xb2 => KIL,
            0xb3 => LAX,
            0xb4 => LDY,
            0xb5 => LDA,
            0xb6 => LDX,
            0xb7 => LAX,
            0xb8 => CLV,
            0xb9 => LDA,
            0xba => TSX,
            0xbb => LAS,
            0xbc => LDY,
            0xbd => LDA,
            0xbe => LDX,
            0xbf => LAX,

            0xc0 => CPY,
            0xc1 => CMP,
            0xc2 => NOP,
            0xc3 => DCP,
            0xc4 => CPY,
            0xc5 => CMP,
            0xc6 => DEC,
            0xc7 => DCP,
            0xc8 => INY,
            0xc9 => CMP,
            0xca => DEX,
            0xcb => AXS,
            0xcc => CPY,
            0xcd => CMP,
            0xce => DEC,
            0xcf => DCP,

            0xd0 => BNE,
            0xd1 => CMP,
            0xd2 => KIL,
            0xd3 => DCP,
            0xd4 => NOP,
            0xd5 => CMP,
            0xd6 => DEC,
            0xd7 => DCP,
            0xd8 => CLD,
            0xd9 => CMP,
            0xda => NOP,
            0xdb => DCP,
            0xdc => NOP,
            0xdd => CMP,
            0xde => DEC,
            0xdf => DCP,

            0xe0 => CPX,
            0xe1 => SBC,
            0xe2 => NOP,
            0xe3 => ISC,
            0xe4 => CPX,
            0xe5 => SBC,
            0xe6 => INC,
            0xe7 => ISC,
            0xe8 => INX,
            0xe9 => SBC,
            0xea => NOP,
            0xeb => SBC,
            0xec => CPX,
            0xed => SBC,
            0xee => INC,
            0xef => ISC,

            0xf0 => BEQ,
            0xf1 => SBC,
            0xf2 => KIL,
            0xf3 => ISC,
            0xf4 => NOP,
            0xf5 => SBC,
            0xf6 => INC,
            0xf7 => ISC,
            0xf8 => SED,
            0xf9 => SBC,
            0xfa => NOP,
            0xfb => ISC,
            0xfc => NOP,
            0xfd => SBC,
            0xfe => INC,
            0xff => ISC,

            _ => panic!("Opcode out of range: {:0>4X}", code),
        }
    }
}
